### ISSUE TITLE
Add a check for partner builds

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#100]
I'd like to add checks to see if partner builds are ready for a given release number.

@mconnormoz @mkaply could you elaborate on how to grab a list of expected builds and in which URL to look for them.
Also do we have them for all channels (Nightly / Beta / Release / ESR) or just a few of them?

My goal is to build some http URL that I can check to see if everything is ready in term of partner builds.

Also do you have partner builds only for Firefox Desktop or also for other products (fennec/focus)?

**Comment by mkaply** [comment]
Some partner repacks go on the public site and others go into a private S3 bucket. I'm not sure this is that simple. Nick Thomas is probably a good person to get ideas on this.

Would this service be able to be used to send emails based on availability of builds?

We do build partner repacks for all channels, but partners mostly care about release (and occasionally beta)

We do not build partner repacks for other products (yet).

**Comment by Natim** [comment]
> Would this service be able to be used to send emails based on availability of builds?

Today we don't plan doing it however if you keep the dashboard open in a table you will get push notification about the status changing.

> Some partner repacks go on the public site

Do you have some examples of links? Where can I find the list of expected partners builds?

> others go into a private S3 bucket.

Ok this is also something that would be possible to check by asking the right permission for PollBot to OPS. As a follow up on the previous question do we have a list of the expected builds that mention if they have to be public or private? Do we need special permissions to access this? Does this list vary between channels?

cc @nthomas-mozilla

**Comment by nthomas-mozilla** [comment]
As Mike says this is more complicated than the main builds we ship, for both technical and confidentiality reasons. Partner builds don't block shipping and aren't time-critical; instead RelEng monitors our release automation for failures. So is it a good fit for the dashboard ? Do you have some docs I can go read about your aims/goals for it ?

**Comment by Natim** [comment]
> Partner builds don't block shipping and aren't time-critical

Good to know.

> RelEng monitors our release automation for failures

Can we in that case add a check for this without divulging confidential information?
We could have a link on the PollBot page that ask for login credentials for more information?

>  Do you have some docs I can go read about your aims/goals for it ?

I guess our only goal is to provide useful information to the Release Management team so that they can validate that their release is live without any issue on any release front.

**Comment by mkaply** [comment]
I think vaildating that there are subdirs in:

http://releases.mozilla.org/pub/firefox/candidates/55.0.3-candidates/build2/partner-repacks/

Is probably enough, keeping in mind that partner-repacks never move out of candidates.

**Comment by Natim** [comment]
Ok thanks a lot, I will do that and then we can iterate in the future.

**Comment by Natim** [comment]
So is it supposed to fail for the last ESR for instance?
http://releases.mozilla.org/pub/firefox/candidates/52.3.0esr-candidates/build2/

When you say all channels, do you include Nightly? If though is there a specific URL for nightly partners builds?

**Comment by Natim** [comment]
You can now see partner-repacks for release and beta: https://mozilla.github.io/delivery-dashboard/#pollbot/firefox/56.0b12

I couldn't find them for ESR and nightly. I will add them if you can provide me with example of the resource URL for those channels.

**Comment by mkaply** [comment]
We don't do repacks for ESR or nightly, so you are good.

Mike
