### ISSUE TITLE
RC build showing incorrectly

### ISSUE THREAD

**Issue by lizzard** [mozilla/PollBot#111]
The dashboard is showing that we are shipping 56.0b12 (with one error) But, right now we are shipping 56.0 (the release candidate) to the beta channel.

**Comment by Natim** [comment]
That's because Product Details still shows 56.0b12 here: https://product-details.mozilla.org/1.0/firefox_versions.json

Any idea where we could find that RELEASE CANDIDATE number?

**Comment by Natim** [comment]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1192197
