### ISSUE TITLE
Check Bedrock links through multiple geographical locations

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/PollBot#145]
During the Release Coordination meeting it was apparent that: 

- our ship time on release day is adjusted 15m to 30m to account for CDN cache TTL lag
- people are anxious and are refreshing the downloads page frequently for links to be available

The [Firefox download links page on mozilla.org](https://www.mozilla.org/en-US/firefox/all/) is behind a CDN.  They are served with a `Cache-Control: max-age=600` (10min) cache.  

A little PollBot robot should just do this. 

- connect to proxy servers in different countries
- fetches the appropriate bedrock download link 
- checks that download link has been updated

**Comment by mostlygeek** [comment]
@pmac what do you think of this proposal?  Would checking CDN edges from different geo locations useful?  Ultimately, I'd like to do is reduce the 15m to 30m CDN refresh consideration we need on release day.

**Comment by pmac** [comment]
There is no longer any reason to wait on the site on release for updated download links. The site now always links to bouncer (download.m.o) with `*-latest` product names. For example, the latest release link for an en-US macOS build would be:

https://download.mozilla.org/?product=firefox-latest-ssl&os=osx&lang=en-US

That link never needs to change. So the new download should be available world-wide at the same time since all that needs to update is bouncer.

**Comment by Natim** [comment]
Ok then we need to change the bedrock task for this new feature.

Right now in nightly and beta we are following the link to check if it links to the good version.

**Comment by pmac** [comment]
Following the link is a good test of bouncer, but the links on the site should now be mostly static. The only exception for now is when a new ESR is released and there are 2 ESR's available for download on the /firefox/organizations/all/ page. The new ESR will have a version number in the download links during that time.

**Comment by mostlygeek** [comment]
Maybe this issue should be expanded instead to add proxy server support into Pollbot.  That way we have a simple library to concurrently fetch resources from multiple geographical locations.  This will let us test if our CDN pops are serving in sync and serving the same content.

**Comment by pmac** [comment]
Changes to the download button links happened in https://bugzilla.mozilla.org/show_bug.cgi?id=937865. Just as an FYI for completeness.

As far as I know the primary thing that still has to wait for CDN is release notes publication. We're working on figuring out how best to make that quick but also resistant to sharp spikes in traffic.
