### ISSUE TITLE
Make sure release notes links are not localized so that they redirects to the right user locale

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#159]
```
 <li id="note-787370">
    <p>Reference link to <a href="https://www.mozilla.com/en-US/firefox/57.0/releasenotes/">57.0 release notes</a></p>
  </li>
```

Here the link should be: https://www.mozilla.com/firefox/57.0/releasenotes/ rather than https://www.mozilla.com/en-US/firefox/57.0/releasenotes/

**Comment by Natim** [comment]
We want to detect that links to the following domain are not set to a specific locale so that they are localized when people click on them.

 - [ ] support.mozilla.org
 - [ ] mozilla.org,
 - [ ] developer.mozilla.org (MDN)

**Comment by Natim** [comment]
Locale files: https://hg.mozilla.org/releases/mozilla-release/raw-file/3702966a64c80e17d01f613b0a464f92695524fc/browser/locales/all-locales

**Comment by sylvestre** [comment]
Should be
https://hg.mozilla.org/releases/mozilla-release/raw-file/tip/browser/locales/all-locales (to avoid hardcoding the changeset)
