### ISSUE TITLE
Add a whatsdeployed entry in the contribute.json file.

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#165]
@peterbe Would you like to take this as a first contribution to PollBot? If not don't worry I will tackle it later.

https://pollbot.dev.mozaws.net/v1/api/doc/#!/Utilities/contribute

**Comment by peterbe** [comment]
Sure thing! But it's a bit weird still since there is only a Dev instance of PollBot. Why is there no prod domain for this?

**Comment by Natim** [comment]
We didn't need it so far but we will after the release of the 1.0 :)

**Comment by Natim** [comment]
Is there a way to calculate the short URL or is it a unique ID generated by whatsdeploy? I would like to configure the URL with the deploy URL of the service we are looking at.
