### ISSUE TITLE
Management branch names instead of version

### ISSUE THREAD

**Issue by sylvestre** [mozilla/PollBot#169]
For now, we have:
https://mozilla.github.io/delivery-dashboard/release#pollbot/firefox/57.0.4
It would be nice (for doc purposes for example) to manage also the branch name:
https://mozilla.github.io/delivery-dashboard/release#pollbot/firefox/release

**Comment by Natim** [comment]
We will try to ask [delivery-dashboard](https://github.com/mozilla/delivery-dashboard/issues/151) to figure out the version automatically before calling PollBot.
