### ISSUE TITLE
Sometimes the release notes don't return a 404 but are not yet published either

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#182]
![incomplete](https://user-images.githubusercontent.com/229453/35558931-8edb5d54-05a9-11e8-8e4e-429cced5d5d5.png)

In that case we want to use an incomplete state.

**Comment by sylvestre** [comment]
I think we still want to have a 404 when the content isn't available.

**Comment by Natim** [comment]
The issue is that today we only handle 200 and 404 but we might also have a 200 with a coming soon message. That's when we will display an incomplete state.

If you think the coming soon message should return a 404 instead of a 200 I guess that's an issue to file in Bedrock.

**Comment by Natim** [comment]
@sylvestre Did you mean having missing instead of incomplete when they are into the coming soon state?

**Comment by sylvestre** [comment]
I was bikesheding about 200 vs 404, do what you want :) I won't waste more of your time on this!
