### ISSUE TITLE
In order to setup automated deployments we need automated testing of the deployed stack.

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#189]
I guess it might be good enough to call:
- once all the checks
- once the heartbeat endpoint

**Comment by magopian** [comment]
Can you give more context please? Are you talking about a travis (or another CI) integration here?
But there's already travis, so I don't understand what "automated testing" means?

**Comment by Natim** [comment]
We are talking about a Jenkins job to validate the stack, something like: https://github.com/Kinto/kinto-integration-tests

**Comment by mostlygeek** [comment]
Ultimately it's on ops/qa's to automate the deployment and promotion.   We should be focused primarily on: 

- making sure `__heartbeat__` is good / reliable way to monitor the service. Though I'm not sure what that really means. Pollbot only breaks when the things it checks are down or changed in ways we haven't anticipated.  
- making we automate container publishing with circleci, (Dockerflow)

**Comment by Natim** [comment]
Both dots are already covered.

**Comment by Natim** [comment]
https://github.com/mozilla-services/pollbot-integration-tests
