### ISSUE TITLE
Add a test to validate blocklist.xml last modified value

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#190]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1436469#c4

**Comment by leplatrem** [comment]
Do you really think this is scope of this project?

I think it should be more in the QA toolbox than here. No?

**Comment by Natim** [comment]
We can probably put it in https://github.com/Kinto/kinto-integration-tests if you want.

**Comment by leplatrem** [comment]
Yeah let's do that. @chartjes f?

**Comment by chartjes** [comment]
@leplatrem 👍
