### ISSUE TITLE
Problems pulling crash data

### ISSUE THREAD

**Issue by lizzard** [mozilla/PollBot#219]
The results from crash-stats just say "hits".  
https://mozilla.github.io/delivery-dashboard/#pollbot/firefox/62.0b12 

This might be from recent changes in Socorro.  If this stat is based on ADI, ADI was just deprecated/removed)

**Comment by mostlygeek** [comment]
Well that's sad.  Talking to telemetry team to switch the data for uptake over to mission control from crashstats.

**Comment by mostlygeek** [comment]
@lizzard this poll is for uptake data from CrashStats.  We already have the telemetry one do you need both or should we just remove this check?

**Comment by mostlygeek** [comment]
Talked to willkg.  The [Crashstats ADI isn't coming back](https://bugzilla.mozilla.org/show_bug.cgi?id=1369498) so we'll just delete it from pollbot as well.
