### ISSUE TITLE
handle changes to /firefox/all/

### ISSUE THREAD

**Issue by willkg** [mozilla/PollBot#247]
The `/firefox/all/` page was redesigned:

https://github.com/mozilla/bedrock/commit/c9cdeb4041961a6bb7c049b6b8d80ba953e61903

That's causing the `test_release_bouncer_download_links` test to fail (and it's probably broken in the PollBot prod, too).

**Comment by willkg** [comment]
It's definitely broken in PollBot. It's causing a red box for the bouncer check on delivery dashboard:

![image](https://user-images.githubusercontent.com/820826/60372735-a3618980-99cb-11e9-9a47-99af13b90769.png)

**Comment by willkg** [comment]
@pmac said that the page hasn't been fully translated, yet. So right now this is the old page:

https://www.mozilla.org/de/firefox/all/

That may not be true for much longer. I'll see if I can tackle this next week.

**Comment by lizzard** [comment]
Came here to say I noticed this today as I went to check on the Firefox 70 release.

**Comment by willkg** [comment]
I was never able to work on this further. The `de` page has been updated now, so I'm not sure how I'd go about trying to figure out what PollBot used to do in order to figure out how to update it. It might be possible to find an older version of that mozilla.org page and go from there.

**Comment by jcristau** [comment]
I wonder if it'd be acceptable to just remove the indirection through www.m.o and just look at bouncer directly.  Once upon a time bedrock used versioned URLs but nowadays it all goes through bouncer -latest links so I'm not sure the indirection has value.

**Comment by pmac** [comment]
> Once upon a time bedrock used versioned URLs but nowadays it all goes through bouncer -latest links so I'm not sure the indirection has value.

+1 for this. Bedrock no longer uses any versioned links for downloads, so you can know up-front all of the download URLs.
