### ISSUE TITLE
We should also check the json files on ship-it

### ISSUE THREAD

**Issue by sylvestre** [mozilla/PollBot#37]
This is on the vpn only but it would be helpful to check also https://ship-it.mozilla.org/json/1.0/firefox_versions.json 
because it would help to identify where a potential issue is coming from.

**Comment by mostlygeek** [comment]
see issue #69 on a request for comment on how pollbot inside the cloudops aws account can talk to shipit which exists on SCL3.

**Comment by Natim** [comment]
#wontfix
