### ISSUE TITLE
API endpoints should have Cache-Control headers

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/PollBot#43]
API responses should return Cache-Control headers. It should be configurable via an environment variable and I suggest a 30second default.

**Comment by Natim** [comment]
Can we handle that at the NGINX level?

**Comment by Natim** [comment]
Here is the config I use in dev:

```
proxy_cache_path /tmp/cache keys_zone=pollbot_cache:30m inactive=60m;

server {
    listen                8080;

    location /v1 {
        proxy_cache pollbot_cache;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_intercept_errors on;
        proxy_pass http://127.0.0.1:8000;
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        proxy_cache_valid any 30s;
        proxy_cache_lock on;
        proxy_cache_use_stale updating;
    }


    location /nginx_status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
    }

    location / {
        return 301 https://$host/v1$request_uri;
    }
}
```

**Comment by mostlygeek** [comment]
> Can we handle that at the NGINX level?
Yup. By default nginx respects the Cache-Control header and will cache things with the rules defined by the app. 

In some cases we may want nginx to override what the app says. In PollBot's case we should have Cache-Control headers. It'll also make it easier for ops as their openresty setup respects Cache-Control by default (at least for Dockerflow'd projects).

**Comment by Natim** [comment]
Ok, do you know what are the Cache-Control you want? Just the max-age one?

**Comment by mostlygeek** [comment]
The directives we use should be appropriate to the endpoint. Though for Version 1.0, `Cache-Control: public; max-age=30` is probably appropriate. 

The `__version__`, `__lbheartbeat__` and `__heartbeat__` endpoints should probably be have `Cache-Control: no-cache`.

**Comment by Natim** [comment]
Should we make it configurable from env variable per endpoints?

**Comment by mostlygeek** [comment]
no. if somebody wants to tweak it we can do it as a new feature with a new issue.
