### ISSUE TITLE
Test that the release have been made for all platform and locales

### ISSUE THREAD

**Issue by leplatrem** [mozilla/PollBot#48]
I think the `archives` task lacks some safety checks:
* should not return True if CDN returns 50X, 302, ...
* should raise TaskError on `aiohttp.ClientError`
* should probably return True only if installers are published in every sub-folders? in every languages/plaftforms? (`incomplete` status?)

**Comment by Natim** [comment]
I agree with you that we can improve the error handling. I opened #75 and #76 about that.

> should probably return True only if installers are published in every sub-folders? in every languages/plaftforms? (incomplete status?)

Let me elaborate on this specific one.

@sylvestre Is it something you would be interested in?
If yes, do we have a way to get the list of expected locale for a release?

**Comment by Natim** [comment]
After thinking about this, I think it is fine not to do it because the delivery-dashboard or PollBot are not supposed to be a QA tool but rather an information tool. I suppose that we already have QA that will tell if some platform or locale are missing from the release but that's not the goal of the current checks.

We can reconsider if we encounter related matters in the future.

**Comment by Natim** [comment]
After a meeting with Release Management, this information is interesting.

- The list of languages can be found here: https://product-details.mozilla.org/1.0/languages.json

**Comment by Natim** [comment]
The list of expected platform is: `linux32, linux64, macosx, win32, win64`

**Comment by Natim** [comment]
Err languages.json doesn't contain the list of locale to ship, we can find them here: https://hg.mozilla.org/mozilla-central/file/tip/browser/locales/shipped-locales

**Comment by Natim** [comment]
Or maybe https://product-details.mozilla.org/1.0/firefox_primary_builds.json keys is a good set as well.

**Comment by Natim** [comment]
After having discussed this furthermore with our stakeholders we decided that the source of truth should be Product-Details.

Here is the plan:

- Download `https://product-details.mozilla.org/1.0/firefox_primary_builds.json`
- Get all the locales that have the given channel define in them
- Make sure the files exists for this list of locale.

**Comment by Natim** [comment]
I did that be then it only works for the last releases because product-details only keep the information for the last ones.

Maybe I will try to give a shot at guessing the tag name in mercurial and see how it goes.
