### ISSUE TITLE
Add an endpoint to list ongoing versions

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#52]
https://github.com/mozilla/delivery-dashboard/issues/12

At least the stuff listed here:
https://product-details.mozilla.org/1.0/firefox_versions.json

- "FIREFOX_NIGHTLY"
- "FIREFOX_AURORA"
- "FIREFOX_ESR"
- "LATEST_FIREFOX_DEVEL_VERSION"
- "LATEST_FIREFOX_VERSION"

**Comment by Natim** [comment]
@sylvestre are we keeping AURORA here on purpose or should we ignore it since it is not going to change anymore?

**Comment by sylvestre** [comment]
You can ignore it. We are keeping because an empty value as usual less
impact then a missing key... And we don't know all consumers of this API

Le mer. 9 août 2017 à 17:42, Rémy HUBSCHER <notifications@github.com> a
écrit :

**Comment by Natim** [comment]
https://ship-it.mozilla.org/json/1.0/firefox_versions.json
and 
https://product-details.mozilla.org/1.0/firefox_versions.json

Both says that the last devedition is 55.0b13 while in bedrock it tries to download 55.0b14 

Also what is the key in product details and ship it firefox version for beta?

**Comment by Natim** [comment]
Just to be sure:

    - nightly : "FIREFOX_NIGHTLY"
    - aurora : "FIREFOX_AURORA" (but we can ignore it since we are building a new API)
    - esr: "FIREFOX_ESR"
    - beta: "LATEST_FIREFOX_DEVEL_VERSION"
    - release: "LATEST_FIREFOX_VERSION"

Is that correct?

**Comment by Natim** [comment]
@pascalchevrel tells me that you might already have a spec for the new endpoint.
I might just go with the same spec for this one if possible.

**Comment by Natim** [comment]
Apparently it is not related: https://bugzilla.mozilla.org/show_bug.cgi?id=1347119

**Comment by mostlygeek** [comment]
What does "ongoing version" mean?

**Comment by Natim** [comment]
> What does "ongoing versions" means?

I though it was self describing but you are the second native english speaker to ask me about it.
It is the last version for each Firefox release channels.

I added it in the Glossary: https://wiki.mozilla.org/Glossary#O
