### ISSUE TITLE
Show history of state transitions for each category

### ISSUE THREAD

**Issue by rkothari19** [mozilla/PollBot#64]
It would be nice to enhance the state "exists"/"incomplete"/"missing" with a timestamp of last poll. Also a timestamp of when the state transitions from incomplete/missing to exists. This will help us remember when the release went live, sec adv went live. Only the timestamp of first-exists matters and not the subsequent ones, except when "exists" transitions to say "missing".

**Comment by Natim** [comment]
Currently it is synchronous we don't keep track of the statuses locally.

**Comment by Natim** [comment]
Currently PollBot is used to check things but does not have a database. I am going to close this as wontfix until we change the architecture to make it stateful.
