### ISSUE TITLE
Apparently the checks for nightly are not looking at the good repository.

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#95]
@pascalchevrel could you give me the correct URLs to check for the nightly archives?

**Comment by Natim** [comment]
According to @jcristau on IRC:

> s/date/mozilla-central/

**Comment by Natim** [comment]
So I guess:

- https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/
and 
- https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/

**Comment by pascalchevrel** [comment]
yes, also the en-US builds are now also in latest-mozilla-central-l10n (wasn't the case until recently) so I don't know if you need to also check latest-mozilla-central

**Comment by Natim** [comment]
Fixed by https://github.com/mozilla/PollBot/pull/96
