### ISSUE TITLE
Add a task to fetch the uptake

### ISSUE THREAD

**Issue by Natim** [mozilla/PollBot#97]
- 1) Get the client count for the target channel from the client_count table -> https://docs.telemetry.mozilla.org/datasets/batch_view/client_count/reference.html
- 2) COUNT(*) and group by (target_version, target_build_id) just for the target channel/desired ping reason (success) 

```
WITH sample AS (
    SELECT payload, date_parse(submission_date_s3, '%Y%m%d') AS submission_date
    FROM telemetry_update_parquet
)
SELECT COUNT(*), payload.target_version, payload.target_build_id
FROM sample
GROUP BY 2,3
```

**Comment by Natim** [comment]
Here is the query @leplatrem came up with:

```
WITH sample AS (
    SELECT normalized_channel AS channel
    FROM client_count
    WHERE app_version = '55.0.3'
    AND activity_date > '2017-09-14'
)
SELECT SUM(CASE WHEN channel = 'release' THEN 1.0 ELSE 0.0 END) / COUNT(*) AS proportion, COUNT(*) AS total
FROM sample
```

**Comment by Natim** [comment]
Here is a query that gives beta uptake.

```
WITH updated_t AS (
    SELECT COUNT(*) AS updated, payload.target_version as target_version, payload.target_build_id as target_build_id
    FROM telemetry_update_parquet
    WHERE payload.reason = 'ready'
      AND payload.target_channel = 'beta'
      AND payload.target_version LIKE '56%'
      GROUP BY 2,3
      ORDER BY 3 DESC
      LIMIT 1
),
total_t AS (
    SELECT COUNT(*) AS total
    FROM client_count
    WHERE normalized_channel = 'beta'
      AND activity_date > '2017-09-14'
)
SELECT updated * 1.0 / total, target_version, target_build_id, updated, total
FROM updated_t, total_t
```

**Comment by leplatrem** [comment]
Note: obtain the build id of a particular version:
`http https://buildhub.stage.mozaws.net/v1/buckets/build-hub/collections/releases/records\?target.version\=56.0b12 | jq -r '.data[] | .build.id' | sort -u`

**Comment by Natim** [comment]
```sudo apt install jq```

```
$ curl -L https://buildhub.stage.mozaws.net/v1/buckets/build-hub/collections/releases/records\?target.version\=56.0b12 2>/dev/null | jq -r '.data[] | .build.id' | sort -u
20170914024831
```

**Comment by Natim** [comment]
For nightly something like that would work: https://sql.telemetry.mozilla.org/queries/36807/source

**Comment by Natim** [comment]
Using ping success: https://sql.telemetry.mozilla.org/queries/36807/source

**Comment by Natim** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1400921

**Comment by Natim** [comment]
We could also temporarily use https://crash-stats.mozilla.com/api/ADI/?end_date=2017-09-17&platforms=Windows&platforms=Linux&platforms=Mac%20OS%20X&product=Firefox&start_date=2017-09-17&versions=56.0b

**Comment by Natim** [comment]
The current way for @calixteman to calculate the uptake is to use the Socorro data.

It uses https://crash-stats.mozilla.com/api/ADI/?end_date=2017-09-16&platforms=Windows&platforms=Linux&platforms=Mac%20OS%20X&product=Firefox&start_date=2017-09-16&versions=56.0b to get the ADI of the current day and calculate the number of people using the current version with regards to the total number of people of the major beta.
